# Generated by Django 4.1.7 on 2023-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_tag_review_todo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
